apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  ignoreDifferences:
  - jsonPointers:
    - /spec/volumeName
    kind: PersistentVolumeClaim
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
  destination:
    namespace: b02-paper-minecraft
  source:
    helm:
      valuesObject:
        serviceAnnotations:
          "lbipam.cilium.io/ips": "192.168.1.237"
        extraEnv:
          MC_HEALTH_EXTRA_ARGS: "--use-proxy"
        persistence:
          dataDir:
            Size: 100Gi
        minecraftServer:
          motd: "§b❣ §f§oLet's have an §b§oice §f§otime together §b❣ §f§n§oS§b§n§ot§f§n§oa§b§n§oy§f§n§o f§b§n§or§f§n§oo§b§n§os§f§n§ot§b§n§oy§b ☺"
          version: "1.21.8"
          maxTickTime: 60000
          difficulty: normal
          levelSeed: "7830518263619659759"
          whitelist: McKency, icykhaye, Moffoso
          icon: "https://raw.githubusercontent.com/kubelize/kube-projects/refs/heads/dev/environments/home-mck/inventory/src/assets/minecraft-icyk-snow-icon.png"
          viewDistance: 12
          memory: "6144M"
          jvmXXOpts: "-Djava.net.preferIPv4Stack=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
          pluginUrls:
            - https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.4.2/PAPER/ViaVersion-5.4.2.jar
            - https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/5.4.2/PAPER/ViaBackwards-5.4.2.jar
            - https://hangarcdn.papermc.io/plugins/pop4959/Chunky/versions/1.4.40/PAPER/Chunky-Bukkit-1.4.40.jar
            - https://hangarcdn.papermc.io/plugins/GriefPrevention/GriefPrevention/versions/16.18.4/PAPER/GriefPrevention%2016.18.4.jar
            - https://mediafilez.forgecdn.net/files/6783/360/FishRewards-1.6.6.jar
            - https://hangarcdn.papermc.io/plugins/Gecolay/GSit/versions/2.4.3/PAPER/GSit-2.4.3.jar
            - https://hangarcdn.papermc.io/plugins/Blue/BlueMap/versions/5.11/PAPER/bluemap-5.11-paper.jar
            - https://hangarcdn.papermc.io/plugins/NichoGX/DiscordRoleSync/versions/2.3.3/PAPER/discord_role_sync-2.3.3.jar
            - https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar
            - https://cdn.modrinth.com/data/s86X568j/versions/asaBBItO/ChunkyBorder-Bukkit-1.2.23.jar
            - https://cdn.modrinth.com/data/6G0lCDWV/versions/u9tkIHXP/BlueMap-BannerMarker.jar
            - https://hangarcdn.papermc.io/plugins/Archy/AuraSkills/versions/2.3.7/PAPER/AuraSkills-2.3.7.jar
            - https://github.com/DecentSoftware-eu/DecentHolograms/releases/download/2.9.7/DecentHolograms-2.9.7.jar
            - https://github.com/plan-player-analytics/Plan/releases/download/5.6.2965/Plan-5.6-build-2965.jar
            - https://github.com/EssentialsX/Essentials/releases/download/2.21.2/EssentialsX-2.21.2.jar
            - https://download.luckperms.net/1606/bukkit/loader/LuckPerms-Bukkit-5.5.17.jar
            - https://github.com/TechnicJelle/BlueMapPlayerControl/releases/download/v1.6/BlueMapPlayerControl-1.6.jar
            - https://cdn.modrinth.com/data/a8UoyV2h/versions/es8eJc4A/bmm-paper-2.1.11.jar
            - https://github.com/LeBogoo/BluemapClaims/releases/download/v1.21.8-1.3/BluemapClaims-1.21.8-1.3.jar
            - https://cdn.modrinth.com/data/gyVHmXm2/versions/9DByHGT5/PickupBuddingAmethyst-1.21-2.jar
            - https://hangarcdn.papermc.io/plugins/henkelmax/SimpleVoiceChat/versions/bukkit-2.5.35/PAPER/voicechat-bukkit-2.5.35.jar
          externalTrafficPolicy: Cluster
          extraPorts:
            - name: plan
              containerPort: 8804
              protocol: TCP
              service:
                annotations:
                  "lbipam.cilium.io/ips": "192.168.1.236"
                enabled: true
                embedded: false
                type: LoadBalancer 
                port: 8804
                targetPort: 8804
              ingress:
                ingressClassName: nginx
                enabled: false
            - name: bluemap
              containerPort: 8100
              protocol: TCP
              service:
                enabled: true
                embedded: false
                type: ClusterIP 
                port: 8100
                targetPort: 8100
              ingress:
                ingressClassName: nginx
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
                hosts:
                  - name: map.icykhaye.xyz
                    path: /
                tls:
                  - secretName: map-tls
                    hosts:
                      - map.icykhaye.xyz
            - name: voip
              containerPort: 24454
              protocol: UDP
              service:
                enabled: true
                embedded: true
                port: 24454
                targetPort: 24454
              ingress:
                ingressClassName: nginx
                enabled: false
        resources:
          requests:
            cpu: 2000m
            memory: 6144Mi
          limits:
            cpu: 4000m
            memory: 8192Mi
        nodeSelector:
          kubernetes.io/hostname: "mck-wk2"