apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a02
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/projects
      path: environments/customers/a02/overlays
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: a02-reserved