apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .customer.name }}-immich"
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      path: postgresql
      targetRevision: 16.7.4
      chart: postgresql
      helm:
        valueFiles:
          - $values/environments/customers/{{ .customer.name }}/overlays/{{ .customer.stage }}/valueFiles/immich/postgresql-values.yaml
    - repoURL: ghcr.io/immich-app/immich-charts
      targetRevision: 0.9.3
      chart: immich
      helm:
        valueFiles:
          - $values/environments/customers/{{ .customer.name }}/overlays/{{ .customer.stage }}/valueFiles/immich/immich-values.yaml
    - repoURL: https://github.com/kubelize/projects
      targetRevision: main
      ref: values