apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
spec:
  storageClassName: "{{ .customer.defaultStorageClass }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi