apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-lobby
  namespace: t99-hytale
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: proxmox
  volumeMode: Filesystem
