apiVersion: v1
kind: Secret
metadata:
  name: ghost-on-kubernetes-mysql-env
  namespace: a01-ghost  # Update with your namespace
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "changeme-root-password"
  MYSQL_DATABASE: "ghost"
  MYSQL_USER: "ghost"
  MYSQL_PASSWORD: "changeme-ghost-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: ghost-config-prod
  namespace: a01-ghost  # Update with your namespace
type: Opaque
stringData:
  config.production.json: |
    {
      "url": "http://localhost:2368",
      "admin": {
        "url": "http://localhost:2368"
      },
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "database": {
        "client": "mysql",
        "connection": {
          "host": "ghost-on-kubernetes-mysql-service",
          "port": 3306,
          "user": "ghost",
          "password": "changeme-ghost-password",
          "database": "ghost"
        }
      },
      "mail": {
        "transport": "Direct"
      },
      "logging": {
        "transports": ["stdout"]
      },
      "process": "local",
      "paths": {
        "contentPath": "/home/nonroot/app/ghost/content"
      }
    }