apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hytale-adventure
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .customer.name }}-hytale"
  source:
    repoURL: https://kubelize.github.io/game-servers/
    targetRevision: 0.2.0
    chart: game-servers
    helm:
      parameters: []
      valuesObject:

        # Hytale Game World Server Values
        # Template for individual game world servers
        # Players are referred here from the lobby

        replicaCount: 1

        # Use StatefulSet for world servers (stable network identity and storage)
        # This gives each replica its own PVC and predictable pod name:
        #   hytale-adventure-0, hytale-adventure-1, hytale-adventure-2
        useStatefulSet: true

        image:
          repository: kubelize/game-servers
          pullPolicy: Always
          tag: "0.2.9-ht-alpha"

        imagePullSecrets: []
        nameOverride: "hytale-adventure"  # Change per world: survival, creative, minigames, etc.
        fullnameOverride: "hytale-adventure"

        serverPasswordSecret:
          useExisting: false
          existingSecretName: ""

        # Game worlds need more storage for player data and chunks
        persistence:
          enabled: true
          storageClassName: "proxmox"
          accessMode: ReadWriteOnce
          size: 20Gi  # Larger for world data

        serverConfig:
          # ===== Core Settings =====
          TZ: "UTC"
          DEBUG: "FALSE"
          PROD: "FALSE"
          SERVER_PORT: "5521"  # Different port per world
          SERVER_IP: "0.0.0.0"
          JAVA_ARGS: "-Xms4G -Xmx8G"

          # ===== Hytale Cache Settings =====
          HYTALE_CACHE: "FALSE"
          HYTALE_CACHE_DIR: "./Server/HytaleServer.aot"

          # ===== Auto-Update Settings =====
          HYTALE_AUTO_UPDATE: "TRUE"  # Check for and download game updates on server start

          # ===== Authentication & Access =====
          HYTALE_ACCEPT_EARLY_PLUGINS: "FALSE"
          HYTALE_ALLOW_OP: "TRUE"  # Allow ops to manage
          HYTALE_AUTH_MODE: ""  # authenticated (default)
          HYTALE_IDENTITY_TOKEN: ""
          HYTALE_SESSION_TOKEN: ""
          HYTALE_OWNER_NAME: "{{ .app.hytale.ownerName }}"
          HYTALE_OWNER_UUID: "{{ .app.hytale.ownerUid }}"

          # ===== Backup Configuration =====
          HYTALE_BACKUP: "TRUE"
          HYTALE_BACKUP_DIR: "./backups"
          HYTALE_BACKUP_FREQUENCY: "60"  # Every hour for game worlds
          HYTALE_BACKUP_MAX_COUNT: "10"

          # ===== Server Options =====
          HYTALE_BARE: "FALSE"
          HYTALE_BOOT_COMMAND: ""
          HYTALE_CLIENT_PID: ""
          HYTALE_DISABLE_ASSET_COMPARE: "FALSE"
          HYTALE_DISABLE_CPB_BUILD: "FALSE"
          HYTALE_DISABLE_FILE_WATCHER: "FALSE"
          HYTALE_DISABLE_SENTRY: "TRUE"
          HYTALE_EVENT_DEBUG: "FALSE"
          HYTALE_FORCE_NETWORK_FLUSH: "true"

          # ===== Schema & Validation =====
          HYTALE_GENERATE_SCHEMA: "FALSE"
          HYTALE_VALIDATE_ASSETS: "FALSE"
          HYTALE_VALIDATE_PREFABS: ""
          HYTALE_VALIDATE_WORLD_GEN: "FALSE"
          HYTALE_SHUTDOWN_AFTER_VALIDATE: "FALSE"

          # ===== Logging =====
          HYTALE_LOG: ""

          # ===== World & Content =====
          HYTALE_MIGRATE_WORLDS: ""
          HYTALE_MIGRATIONS: ""
          HYTALE_UNIVERSE: ""
          HYTALE_WORLD_GEN: ""
          HYTALE_PREFAB_CACHE: ""

          # ===== Mods & Plugins =====
          HYTALE_MODS: ""
          HYTALE_EARLY_PLUGINS: ""

          # ===== Network & Transport =====
          HYTALE_TRANSPORT: ""  # QUIC (default)
          HYTALE_SINGLEPLAYER: "FALSE"

          # ===== Version Control =====
          HYTALE_VERSION: "FALSE"

          # ===== config.json Settings =====
          HYTALE_SERVER_NAME: "🌲 Kubelize Network - Adventure"
          HYTALE_MOTD: "Explore, build, survive!"
          HYTALE_PASSWORD: ""  # Usually empty - access controlled by lobby
          HYTALE_MAX_PLAYERS: "50"
          HYTALE_MAX_VIEW_RADIUS: "12"  # 384 blocks - adjust based on performance
          HYTALE_COMPRESSION: "false"
          HYTALE_WORLD: "world"  # Main world name
          HYTALE_GAMEMODE: "Adventure"  # or "Creative"

          # ===== Web Console Settings =====
          CONSOLE_PORT: "8080"  # Gotty web console port

        # CurseForge Mod Configuration
        curseforge:
          mods: []
            # - server-teleporters
            # - inventory-manager-api
            # - 1440233:7534554
            # - perfect-parries
            # - elitemobs
            # - yungs-hydungeons
            # - partypro
            # - ymmersive-melodies
            # - mdevtools-development-tools
          apiKeySecret:
            name: "curseforge-api-key"
            key: "api-key"
          releaseChannel: "release"
          autoUpdate: true
          failOnError: false
          prune: false
          gameVersionFilter: ""

        serviceAccount:
          create: true
          automount: true
          annotations: {}
          name: ""

        podAnnotations: {}
        podLabels:
          server-type: "world"
          world-name: "adventure"  # Change per world

        podSecurityContext:
          fsGroup: 1000

        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000

        # World servers are accessed via player referral (not directly)
        # Can use ClusterIP for internal-only access
        gameService:
          annotations: {}
          type: LoadBalancer  # External access for cross-server teleport
          ports:
            - name: gameport-udp
              protocol: UDP
              port: 5521  # Unique port per world
              targetPort: 5521
            - name: gameport-tcp
              protocol: TCP
              port: 5520
              targetPort: 5520

        webService:
          enabled: true
          type: ClusterIP
          ports:
            - name: console
              protocol: TCP
              port: 8080
              targetPort: 8080

        ingress:
          enabled: false

        # Game worlds need more resources
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "2"
            memory: "4Gi"

        livenessProbe:
          enabled: false

        readinessProbe:
          enabled: false


        # Volume mounts
        volumeMounts:
          - name: storage
            mountPath: /home/kubelize/server
          - name: backups
            mountPath: /home/kubelize/backups
          - name: pg-ca
            mountPath: /home/kubelize/tls/ca.crt
            subPath: ca.crt
            readOnly: true
            optional: true
          - name: server-config
            mountPath: /home/kubelize/config-data/config-values.yaml
            subPath: config-values.yaml
          - name: server-password
            mountPath: /home/kubelize/config-data/serverpassword.yaml
            subPath: serverpassword.yaml
          - name: machine-id
            mountPath: /etc/machine-id
            subPath: machine-id
            readOnly: true

        # Volumes
        volumes:
          - name: backups
            persistentVolumeClaim:
              claimName: backups-adventure
          - name: pg-ca
            secret:
              secretName: "{{ .customer.name }}-hytale-postgresql-ca-{{ .customer.stage }}"
          - name: server-config
            configMap:
              name: hytale-adventure-config
          - name: server-password
            secret:
              secretName: hytale-adventure-server-password
          - name: machine-id
            configMap:
              name: machine-id
              items:
                - key: machine-id
                  path: machine-id

        nodeSelector: {}
        affinity: {}
        tolerations: []
