apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ce-server
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/kube-projects
      path: apps/stable/gameservers/conan-exiles/deployment
      targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ce-server