apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hytale-postgresql
  namespace: argocd
spec:
  project: default
  destination:
    namespace: "{{ .customer.name }}-hytale"
    server: https://kubernetes.default.svc
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    targetRevision: "*"
    helm:
      parameters: []
      valuesObject:
        clusterName: "{{ .customer.name }}-hytale-postgresql-prod"
        type: postgresql
        version:
          postgresql: "16"
        mode: standalone
        cluster:
          instances: 1
          certificates:
            serverTLSSecret: hytale-postgresql-tls
            serverCASecret: hytale-postgresql-ca
          storage:
            size: 10Gi
            storageClass: proxmox
          postgresql:
            parameters: {}
          bootstrap:
            initdb:
              database: hytale
              owner: hytale
              secret:
                name: hytale-postgresql-auth

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hytale-postgresql-selfsigned
  namespace: "{{ .customer.name }}-hytale"
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hytale-postgresql-ca
  namespace: "{{ .customer.name }}-hytale"
spec:
  isCA: true
  secretName: hytale-postgresql-ca
  issuerRef:
    kind: Issuer
    name: hytale-postgresql-selfsigned
  commonName: hytale-postgresql-ca

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hytale-postgresql-ca-issuer
  namespace: "{{ .customer.name }}-hytale"
spec:
  ca:
    secretName: hytale-postgresql-ca

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hytale-postgresql
  namespace: "{{ .customer.name }}-hytale"
spec:
  secretName: hytale-postgresql-tls
  issuerRef:
    kind: Issuer
    name: hytale-postgresql-ca-issuer
  dnsNames:
    - "{{ .customer.name }}-hytale-postgresql-prod.{{ .customer.name }}-hytale.svc.cluster.local"
  privateKey:
    algorithm: RSA
    size: 2048
