apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hytale-postgresql
  namespace: argocd
spec:
  project: default
  destination:
    namespace: "{{ .customer.name }}-hytale"
    server: https://kubernetes.default.svc
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    targetRevision: "*"
    helm:
      parameters: []
      valuesObject:
        clusterName: "{{ .customer.name }}-hytale-postgresql-prod"
        type: postgresql
        version:
          postgresql: "16"
        mode: standalone
        cluster:
          instances: 1
          certificates:
            serverTLSSecret: "{{ .customer.name }}-hytale-postgresql-tls-{{ .customer.stage }}"
            serverCASecret: "{{ .customer.name }}-hytale-postgresql-tls-{{ .customer.stage }}"
          storage:
            size: 10Gi
            storageClass: proxmox
          postgresql:
            parameters: {}
          bootstrap:
            initdb:
              database: hytale
              owner: hytale
              secret:
                name: hytale-postgresql-auth

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hytale-postgresql-selfsigned
  namespace: "{{ .customer.name }}-hytale"
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hytale-postgresql-ca
  namespace: "{{ .customer.name }}-hytale"
spec:
  isCA: true
  secretName: "{{ .customer.name }}-hytale-postgresql-ca-{{ .customer.stage }}"
  issuerRef:
    kind: Issuer
    name: "{{ .customer.name }}-hytale-postgresql-selfsigned-{{ .customer.stage }}"
  commonName: hytale-postgresql-ca

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hytale-postgresql-ca-issuer
  namespace: "{{ .customer.name }}-hytale"
spec:
  ca:
    secretName: "{{ .customer.name }}-hytale-postgresql-ca-{{ .customer.stage }}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hytale-postgresql
  namespace: "{{ .customer.name }}-hytale"
spec:
  secretName: "{{ .customer.name }}-hytale-postgresql-tls-{{ .customer.stage }}"
  issuerRef:
    kind: Issuer
    name: "{{ .customer.name }}-hytale-postgresql-ca-issuer-{{ .customer.stage }}"
  dnsNames:
    - "{{ .customer.name }}-hytale-postgresql-prod-cluster-rw.{{ .customer.name }}-hytale.svc.cluster.local"
  privateKey:
    algorithm: RSA
    size: 2048
