apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a01
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/projects
      path: environments/customers/a01/overlays
      targetRevision: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: a01-reserved