apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "overleaf"
  namespace: "argocd"
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "{{ .customer.name }}-overleaf"
  source:
    repoURL: https://bedag.github.io/helm-charts
    targetRevision: 2.0.0
    chart: raw
    helm:
      valuesObject:
        resources:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: overleaf
              labels:
                app: overleaf
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: overleaf
              template:
                metadata:
                  labels:
                    app: overleaf
                spec:
                  containers:
                    - name: overleaf
                      image: sharelatex/sharelatex:6.1.0-RC1
                      ports:
                        - name: http
                          containerPort: 80
                      env:
                        - name: OVERLEAF_SITE_URL
                          value: "https://overleaf.{{ .customer.primaryDomain }}"
                        - name: OVERLEAF_APP_NAME
                          value: "Overleaf CE"
                        - name: OVERLEAF_MONGO_URL
                          value: "mongodb://overleaf-mongo:27017/sharelatex"
                        - name: OVERLEAF_REDIS_HOST
                          value: "overleaf-redis"
                        - name: OVERLEAF_REDIS_PORT
                          value: "6379"
                        - name: REDIS_HOST
                          value: "overleaf-redis"
                        - name: REDIS_PORT
                          value: "6379"
                        # Configure these via ejson.
                        - name: OVERLEAF_EMAIL_SMTP_HOST
                          value: ""
                        - name: OVERLEAF_EMAIL_SMTP_PORT
                          value: ""
                        - name: OVERLEAF_EMAIL_SMTP_SECURE
                          value: ""
                        - name: OVERLEAF_EMAIL_SMTP_USER
                          value: ""
                        - name: OVERLEAF_EMAIL_SMTP_PASS
                          value: ""
                        - name: OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH
                          value: ""
                        - name: OVERLEAF_EMAIL_SMTP_IGNORE_TLS
                          value: ""
                        - name: OVERLEAF_EMAIL_SMTP_NAME
                          value: ""
                        - name: OVERLEAF_EMAIL_SMTP_LOGGER
                          value: ""
                        - name: OVERLEAF_CUSTOM_EMAIL_FOOTER
                          value: ""
                      volumeMounts:
                        - name: overleaf-data
                          mountPath: /var/lib/overleaf
                  volumes:
                    - name: overleaf-data
                      persistentVolumeClaim:
                        claimName: overleaf-data

          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: overleaf-redis
              labels:
                app: overleaf-redis
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: overleaf-redis
              template:
                metadata:
                  labels:
                    app: overleaf-redis
                spec:
                  containers:
                    - name: redis
                      image: redis:7.2-alpine
                      ports:
                        - containerPort: 6379
                      args:
                        - "--save"
                        - "60"
                        - "1"
                        - "--appendonly"
                        - "yes"
                      resources:
                        requests:
                          cpu: 50m
                          memory: 128Mi
                        limits:
                          cpu: 250m
                          memory: 256Mi

          - apiVersion: apps/v1
            kind: StatefulSet
            metadata:
              name: overleaf-mongo
              labels:
                app: overleaf-mongo
            spec:
              serviceName: overleaf-mongo
              replicas: 1
              selector:
                matchLabels:
                  app: overleaf-mongo
              template:
                metadata:
                  labels:
                    app: overleaf-mongo
                spec:
                  containers:
                    - name: mongo
                      image: mongo:8.0
                      ports:
                        - containerPort: 27017
                      args:
                        - "--storageEngine"
                        - wiredTiger
                        - "--replSet"
                        - rs0
                      lifecycle:
                        postStart:
                          exec:
                            command:
                              - /bin/sh
                              - -ec
                              - |
                                # Wait for mongod to accept connections on localhost
                                until mongosh --quiet --host 127.0.0.1 --eval 'db.runCommand({ping:1}).ok' | grep -q 1; do
                                  sleep 1
                                done

                                # Initiate replica set only once (idempotent)
                                mongosh --quiet --host 127.0.0.1 --eval '
                                  try {
                                    rs.status()
                                  } catch (e) {
                                    rs.initiate({
                                      _id: "rs0",
                                      members: [
                                        { _id: 0, host: "'"$HOSTNAME"'.overleaf-mongo:27017" }
                                      ]
                                    })
                                  }
                                '
                      volumeMounts:
                        - name: mongo-data
                          mountPath: /data/db
                      resources:
                        requests:
                          cpu: 100m
                          memory: 256Mi
                        limits:
                          cpu: 500m
                          memory: 512Mi
              volumeClaimTemplates:
                - metadata:
                    name: mongo-data
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 10Gi

          - apiVersion: v1
            kind: Service
            metadata:
              name: overleaf
              labels:
                app: overleaf
            spec:
              selector:
                app: overleaf
              ports:
                - name: http
                  port: 80
                  targetPort: http
              type: ClusterIP

          - apiVersion: v1
            kind: Service
            metadata:
              name: overleaf-redis
              labels:
                app: overleaf-redis
            spec:
              selector:
                app: overleaf-redis
              ports:
                - port: 6379
                  targetPort: 6379
              type: ClusterIP

          - apiVersion: v1
            kind: Service
            metadata:
              name: overleaf-mongo
              labels:
                app: overleaf-mongo
            spec:
              clusterIP: None
              publishNotReadyAddresses: true
              selector:
                app: overleaf-mongo
              ports:
                - port: 27017
                  targetPort: 27017

          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: overleaf
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
                nginx.ingress.kubernetes.io/proxy-body-size: "100m"
            spec:
              ingressClassName: "{{ .cluster.defaultIngressClass }}"
              rules:
                - host: "overleaf.{{ .customer.primaryDomain }}"
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: overleaf
                            port:
                              number: 80
              tls:
                - hosts:
                    - "overleaf.{{ .customer.primaryDomain }}"
                  secretName: overleaf-tls

          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: overleaf-data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
              storageClassName: "{{ .cluster.defaultStorageClass }}"
