apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "linkstack"
  namespace: "argocd"
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkstack
  source:
    repoURL: https://bedag.github.io/helm-charts
    targetRevision: 2.0.0
    chart: raw
    helm:
      valuesObject:
        resources:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: linkstack
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: linkstack
              template:
                metadata:
                  labels:
                    app: linkstack
                spec:
                  initContainers:
                    - name: copy-htdocs
                      image: linkstackorg/linkstack:latest
                      command:
                        - /bin/ash
                        - -c
                        - |
                          apk add --no-cache rsync && sleep 1 && \
                          if [ -z "$(ls -A /htdocs_provisioning | grep -v '^lost+found$')" ]; then
                            rsync -a --exclude='lost+found' /htdocs/ /htdocs_provisioning/ && \
                            chown -R apache:apache /htdocs_provisioning && \
                            chown -R apache:apache /htdocs && \
                            find /htdocs -type d -print0 | xargs -0 chmod 0755 && \
                            find /htdocs -type f -print0 | xargs -0 chmod 0644 && \
                            echo "/htdocs was empty. Files copied to /htdocs_provisioning."
                          else
                            echo "/htdocs_provisioning is not empty. No files copied."
                          fi
                      volumeMounts:
                        - name: linkstack-storage
                          mountPath: /htdocs_provisioning
                  containers:
                    - name: linkstack
                      image: kubelize/linkstack:0.1.2
                      # command: ["/bin/ash", "-c", "sleep 3600"]
                      ports:
                        - name: http
                          containerPort: 80
                      # securityContext:
                      #   runAsUser: 100
                      #   runAsGroup: 101
                      #   fsGroup: 101
                      livenessProbe:
                        httpGet:
                          path: /
                          port: http
                          httpHeaders:
                          - name: User-Agent
                            value: LivenessProbe
                        initialDelaySeconds: 1
                        periodSeconds: 5
                        failureThreshold: 2
                        timeoutSeconds: 3
                      readinessProbe:
                        httpGet:
                          path: /
                          port: http
                          httpHeaders:
                          - name: User-Agent
                            value: ReadinessProbe
                        initialDelaySeconds: 1
                        periodSeconds: 5
                        failureThreshold: 2
                        timeoutSeconds: 3
                      env:
                        - name: TZ
                          value: "Europe/Berlin"
                        - name: HTTP_SERVER_NAME
                          value: "{{ .customer.primaryDomain }}"
                        - name: LOG_LEVEL
                          value: "info"
                        - name: PHP_MEMORY_LIMIT
                          value: "512M"
                        - name: UPLOAD_MAX_FILESIZE
                          value: "16M"
                      volumeMounts:
                        - name: linkstack-storage
                          mountPath: /htdocs
                  volumes:
                    - name: linkstack-storage
                      persistentVolumeClaim:
                        claimName: linkstack-pvc
          - apiVersion: v1
            kind: Service
            metadata:
              name: linkstack
            spec:
              selector:
                app: linkstack
              ports:
                - name: http
                  port: 80
                  targetPort: http
              type: ClusterIP
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: linkstack
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
                nginx.ingress.kubernetes.io/proxy-body-size: "100m"
            spec:
              ingressClassName: "{{ .cluster.defaultIngressClass }}"
              rules:
                - host: "{{ .customer.primaryDomain }}"
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: linkstack
                            port:
                              number: 80
              tls:
                - hosts:
                    - "{{ .customer.primaryDomain }}"
                  secretName: linkstack-tls
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: linkstack-pvc
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
