apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: "{{ .customer.name }}-reserved"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: "{{ .customer.name }}-{{ .customer.project }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .customer.name }}-jupyterhub-{{ .customer.stage }}"
  source:
    repoURL: https://jupyterhub.github.io/helm-chart
    targetRevision: 4.3.2
    chart: jupyterhub
    helm:
      valuesObject:
        rbac:
          create: true
        proxy:
          service:
            type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: "{{ .cluster.defaultIngressClass }}"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
          hosts:
            - jupyter.{{ .customer.primaryDomain }}
          tls:
            - secretName: jupyterhub-tls
              hosts:
                - jupyter.{{ .customer.primaryDomain }}
        hub:
          serviceAccount:
            create: true
            annotations: {}
          networkPolicy:
            enabled: true
            egressAllowRules:
              cloudMetadataServer: true
              dnsPortsCloudMetadataServer: true
              dnsPortsKubeSystemNamespace: true
              dnsPortsPrivateIPs: true
              nonPrivateIPs: true
              privateIPs: true
            egress:
              - to:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: default
                ports:
                  - protocol: TCP
                    port: 6443
                  - protocol: TCP
                    port: 443
          extraEnv:
            JUPYTERHUB_KUBERNETES_REQUEST_TIMEOUT: "120"
          config:
            JupyterHub:
              authenticator_class: github
            GitHubOAuthenticator:
              client_id: "{{ .ejson.jupyterhub.github.clientId }}"
              client_secret: "{{ .ejson.jupyterhub.github.clientSecret }}"
              oauth_callback_url: "https://jupyter.{{ .customer.primaryDomain }}/hub/oauth_callback"
              scope:
                - read:user
            Authenticator:
              admin_users:
                - "{{ .ejson.jupyterhub.adminUser }}"
              allowed_users:
                - "{{ .ejson.jupyterhub.adminUser }}"
            KubeSpawner:
              k8s_api_request_timeout: 180
              k8s_api_request_retry_timeout: 300
              http_timeout: 180
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 1000m
        singleuser:
          defaultUrl: /lab
          image:
            name: quay.io/jupyter/scipy-notebook
            tag: "python-3.11"
          storage:
            type: dynamic
            dynamic:
              storageClass: "{{ .cluster.defaultStorageClass }}"
            capacity: 20Gi
          cpu:
            limit: 2
            guarantee: 0.5
          memory:
            limit: 4G
            guarantee: 1G
          startTimeout: 600
        cull:
          enabled: true
          timeout: 3600
          every: 300
          users: true
