apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: b01
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/kube-projects
      path: tenants/b01/apps/
      targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: b01-reserved