apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
  namespace: "{{ .customer.name }}-reserved"
spec:
  project: "{{ .customer.name }}-{{ .customer.project }}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
  source:
    repoURL: https://bedag.github.io/helm-charts
    targetRevision: 2.0.0
    chart: raw
    helm:
      valuesObject:
        resources:
        - apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
            template:
              metadata:
                labels:
                  app: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
              spec:
                containers:
                  - name: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
                    image: kubelize/web-rcon:1.0.1
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 443
                    volumeMounts:
                      - name: secret-volume
                        mountPath: /home/kubelize/rcon.yaml
                        subPath: rcon.yaml
                volumes:
                  - name: secret-volume
                    secret:
                      secretName: rcon-config
        - apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: vault-auth
        - apiVersion: secrets.hashicorp.com/v1beta1
          kind: VaultAuth
          metadata:
            name: web-rcon
          spec:
            method: kubernetes
            mount: kubernetes
            kubernetes:
              role: "{{ .customer.name }}-read"
              serviceAccount: vault-auth
              audiences:
                - vault
        - apiVersion: secrets.hashicorp.com/v1beta1
          kind: VaultStaticSecret
          metadata:
            name: rcon-config
          spec:
            type: kv-v2
            mount: "kv-{{ .customer.name }}"
            path: web-rcon/rcon-config
            vaultAuthRef: web-rcon
            refreshAfter: 1m
            destination:
              create: true
              overwrite: true
              name: rcon-config
              type: Opaque
            rolloutRestartTargets:
              - kind: Deployment
                name: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
        - apiVersion: v1
          kind: Service
          metadata:
            name: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}-service"
          spec:
            selector:
              app: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
            ports:
              - protocol: TCP
                port: 443
                targetPort: 443
