apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: namespace-baseline
  namespace: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: teleport-kube-agent
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: ingress-nginx
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: "{{ .customer.name }}-web-rcon-{{ .customer.stage }}"
    - toEndpoints:
        - matchExpressions:
            - key: k8s:io.kubernetes.pod.namespace
              operator: In
              values:
                - "{{ .customer.name }}-minecraft"
                - "{{ .customer.name }}-minecraft-{{ .customer.stage }}"
                - "{{ .customer.name }}-paper-minecraft-{{ .customer.stage }}"
                - "{{ .customer.name }}-sdtd-{{ .customer.stage }}"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toEntities:
        - kube-apiserver
