apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - name: test-container
    image: busybox:latest
    command: ["/bin/sh"]
    args:
      - -c
      - while true; do echo "Environment variable: $TEST_VAR"; sleep 5; done
    env:
    - name: TEST_VAR
      value: "{{ .ejson.openWebui.clientId }}"
  restartPolicy: Never