image:
  repository: tensorchord/pgvecto-rs
  tag: pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
global:
  security:
    allowInsecureImages: true
  postgresql:
    auth:
      database: immich
primary:
  resourcesPreset: "medium"
  containerSecurityContext:
    readOnlyRootFilesystem: false
  initdb:
    scripts:
      create-extensions.sql: |
        CREATE EXTENSION cube;
        CREATE EXTENSION earthdistance;
        CREATE EXTENSION vectors;