apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .customer.name }}-open-webui"
  source:
    repoURL: https://helm.openwebui.com/
    targetRevision: 8.14.0
    chart: open-webui
    helm:
      valuesObject:
        persistence:
          enabled: true
          size: 20Gi
        image:
          # -- Open WebUI image tag (Open WebUI image tags can be found here: https://github.com/open-webui/open-webui)
          # @section -- Image configuration
          tag: "0.8.1"
        sso:
          enabled: true
          mergeAccountsByEmail: true
          oidc:
            # -- Enable OIDC authentication
            # @section -- OIDC configuration
            enabled: true
            # -- OIDC client ID
            # @section -- OIDC configuration
            clientId: "{{ .ejson.openWebui.clientId }}"
            # -- OIDC client secret (ignored if clientExistingSecret is set)
            # @section -- OIDC configuration
            clientSecret: "{{ .ejson.openWebui.clientSecret }}"
            # -- OICD client secret from existing secret
            # @section -- OIDC configuration
            providerUrl: "{{ .ejson.openWebui.providerUrl }}"
            # -- Name of the provider to show on the UI
            # @section -- OIDC configuration
            providerName: "kubelize auth0"
            # -- Scopes to request (space-separated).
            # @section -- OIDC configuration
            scopes: "openid email profile"
