apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .customer.name }}-open-webui"
  sources:
    - repoURL: https://helm.openwebui.com/
      targetRevision: 8.14.0
      chart: open-webui
      helm:
        valuesObject:
          persistence:
            enabled: true
            size: 20Gi
        valueFiles:
          - $values/environments/customers/{{ .customer.name }}/overlays/{{ .customer.stage }}/valueFiles/open-webui/open-webui-values.yaml
