apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: namespace-baseline
  namespace: "{{ .customer.name }}-nextcloud-{{ .customer.stage }}"
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: "{{ .customer.name }}-nextcloud-{{ .customer.stage }}"
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: ingress-nginx
    - fromEntities:
        - host
        - remote-node
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: "{{ .customer.name }}-nextcloud-{{ .customer.stage }}"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toEntities:
        - world
