apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: "{{ .customer.name }}-reserved"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .customer.name }}-jellyfin-{{ .customer.stage }}"
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.7.0
    chart: jellyfin
    helm:
      valuesObject:
        service:
          type: LoadBalancer
        ingress:
          enabled: false
        jellyfin:
          env:
            - name: TZ
              value: Europe/Zurich
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 4Gi
        persistence:
          config:
            enabled: true
            accessMode: ReadWriteOnce
            size: 500Gi
            storageClass: "{{ .cluster.defaultStorageClass }}"
          media:
            enabled: false
          cache:
            enabled: false
