apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: b01-immich
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: proxmox
  volumeMode: Filesystem
  volumeName: pvc-2ee472f9-4695-4ccf-a741-f89f4b2a8a70