apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  namespace: b01-open-webui
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: proxmox
  volumeMode: Filesystem
  volumeName: pvc-a7f8e72e-d45d-48c1-9ba6-72eb623add65